import os
from dotenv import load_dotenv

load_dotenv()

# Rabbit_MQ Setting
RABBIT_ACCOUNT = os.getenv("RABBIT_ACCOUNT")
RABBIT_PASSWORD = os.getenv("RABBIT_PASSWORD")
RABBIT_HOST = os.getenv("RABBIT_HOST")
RABBIT_PORT = os.getenv("RABBIT_PORT")
EVENT_QUEUE = os.getenv("EVENT_QUEUE")
SOURCE_QUEUE = os.getenv("SOURCE_QUEUE")
TEST_WORKER_QUEUE = os.getenv("TEST_WORKER_QUEUE")
ETL_QUEUE = os.getenv("ETL_QUEUE")
PREDICT_ERROR_QUEUE = os.getenv("PREDICT_ERROR_QUEUE")

# MONGO Setting
MONGO_USER = os.getenv("MONGO_USER")
MONGO_PASSWORD = os.getenv("MONGO_PASSWORD")

MONGO_HOST_EVENT_GO = os.getenv("MONGO_HOST_EVENT_GO")
MONGO_PORT_EVENT_GO = os.getenv("MONGO_PORT_EVENT_GO")

DATABASE_EVENT_GO = os.getenv("DATABASE_EVENT_GO")
BROWSED_EVENT_SOURCE_COLLECTION = os.getenv("BROWSED_EVENT_SOURCE_COLLECTION")
EVENT_SOURCE_AWAITING_CHECK_COLLECTION = os.getenv("EVENT_SOURCE_AWAITING_CHECK_COLLECTION")
EVENT_SOURCE_EXTRACTION_COLLECTION = os.getenv("EVENT_SOURCE_EXTRACTION_COLLECTION")

MONGO_HOST_PAGE = os.getenv("MONGO_HOST_PAGE")
MONGO_PORT_PAGE = os.getenv("MONGO_PORT_PAGE")

MONGO_HOST_PAGE = os.getenv("MONGO_HOST_PAGE")
MONGO_PORT_PAGE = os.getenv("MONGO_PORT_PAGE")

DATABASE_PAGE = os.getenv("DATABASE_PAGE")
QUEUE_COLLECTION = os.getenv("QUEUE_COLLECTION")
AUTO_EXTRACTION_COLLECTION = os.getenv("AUTO_EXTRACTION_COLLECTION")

MONGO_HOST_ETL = os.getenv("MONGO_HOST_ETL")
MONGO_PORT_ETL = os.getenv("MONGO_PORT_ETL")

DATABASE_ETL = os.getenv("DATABASE_ETL")
EXTRACTOR_COLLECTION = os.getenv("EXTRACTOR_COLLECTION")
AUTO_EXTRACTION_URL_COLLECTION = os.getenv("AUTO_EXTRACTION_URL_COLLECTION")
TEMP_EXTRACTED_DATA_COLLECTION = os.getenv("TEMP_EXTRACTED_DATA_COLLECTION")
